// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3AZPfMlrfxfTxliJAMaVIwNKm6tMHvkY',
    appId: '1:566626779962:web:b0ce8f0605821528760603',
    messagingSenderId: '566626779962',
    projectId: 'flutterdgoat',
    authDomain: 'flutterdgoat.firebaseapp.com',
    storageBucket: 'flutterdgoat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_shcWlBT0HYgER4j53CxomaUjXAoY7c0',
    appId: '1:566626779962:android:1109682194df2d0a760603',
    messagingSenderId: '566626779962',
    projectId: 'flutterdgoat',
    storageBucket: 'flutterdgoat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd5NzUECfV9Rk6JUpekl7krWdVC7Bc-v4',
    appId: '1:566626779962:ios:b779809a244d890d760603',
    messagingSenderId: '566626779962',
    projectId: 'flutterdgoat',
    storageBucket: 'flutterdgoat.firebasestorage.app',
    iosBundleId: 'com.attendance.attendanceSystem',
  );
}
